version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 payout_engine.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=payout_engine.settings

  worker:
    build: .
    container_name: celery_worker
    command: celery -A payout_engine worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  beat:
    build: .
    container_name: celery_beat
    command: celery -A payout_engine beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: redis
    restart: always