# Generated by Django 6.0.4 on 2026-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payout_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.EmailField(default='default@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
