# Generated by Django 6.0.4 on 2026-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merchant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
