# Generated by Django 6.0.4 on 2026-04-27 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_event_webhook_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
