# Generated by Django 6.0.4 on 2026-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='snapshot_balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
